### ISSUE TITLE
Need to manage dependencies (dateutil in this case)

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/pydatalab#34]
Here is the code and the output in a Jupyter notebook cell. Expected it to bring in dependencies; instead got this error. Also, shouldn't 2.5.3 of dateutil satisfy the requirement?

%%bash
pip install -i https://testpypi.python.org/pypi datalab

Collecting datalab
  Using cached https://testpypi.python.org/packages/74/54/2654870a38ed720ee9afc3e5924721bff85cb10f25564f288f036c1d196c/datalab-0.1.1606020925-py2-none-any.whl
Collecting python-dateutil==2.5.0 (from datalab)
  Could not find a version that satisfies the requirement python-dateutil==2.5.0 (from datalab) (from versions: )
No matching distribution found for python-dateutil==2.5.0 (from datalab)

**Comment by parthea** [comment]
I encountered a similar error:

```
tony@tony-laptop:~$ pip install -i https://testpypi.python.org/pypi datalab
Collecting datalab
  Using cached https://testpypi.python.org/packages/74/54/2654870a38ed720ee9afc3e5924721bff85cb10f25564f288f036c1d196c/datalab-0.1.1606020925-py2-none-any.whl
Collecting oauth2client==2.0.2 (from datalab)
  Could not find a version that satisfies the requirement oauth2client==2.0.2 (from datalab) (from versions: )
No matching distribution found for oauth2client==2.0.2 (from datalab)
```

Running with the `-vvv` option, I can see it is trying to get the package from the http://testpypi.python.org site, but https://testpypi.python.org/pypi/ does not have oauth2client (or python-dateutil)

```
tony@tony-laptop:~$  pip install -vvv -i https://testpypi.python.org/pypi datalab
Collecting datalab
  1 location(s) to search for versions of datalab:
  * https://testpypi.python.org/pypi/datalab/
  Getting page https://testpypi.python.org/pypi/datalab/
  Looking up "https://testpypi.python.org/pypi/datalab/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): testpypi.python.org
  "GET /pypi/datalab/ HTTP/1.1" 200 15774
  Updating cache with response from "https://testpypi.python.org/pypi/datalab/"
  Analyzing links from page https://testpypi.python.org/pypi/datalab/
    Skipping link http://www.python.org (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi/datalab/#left-hand-navigation (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi/datalab/#content-body (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?%3Aaction=browse (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?%3Aaction=submit_form (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?%3Aaction=list_classifiers (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?%3Aaction=rss (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?%3Aaction=packages_rss (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://wiki.python.org/moin/CheeseShopTutorial (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/security (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://sourceforge.net/tracker/?group_id=66150&atid=513504 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://github.com/pypa/pypi-legacy/issues (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/sigs/distutils-sig/ (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://wiki.python.org/moin/CheeseShopDev (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/about (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/news (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/doc (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/download (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/community (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/psf (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/dev (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi/datalab (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi/datalab/0.1.1606020925 (from https://testpypi.python.org/pypi/datalab/); unsupported archive format: .1606020925
    Skipping link https://testpypi.python.org/pypi?%3Aaction=login_form (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?%3Aaction=register_form (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?%3Aaction=forgotten_password_form (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=openid (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=login&provider=Launchpad (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/google_login (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi/datalab/#downloads (from https://testpypi.python.org/pypi/datalab/); not a file
    Found link https://testpypi.python.org/packages/74/54/2654870a38ed720ee9afc3e5924721bff85cb10f25564f288f036c1d196c/datalab-0.1.1606020925-py2-none-any.whl#md5=80daa08a2415a5a0accf72bb68a018bf (from https://testpypi.python.org/pypi/datalab/), version: 0.1.1606020925
    Skipping link https://testpypi.python.org/pypi?:action=show_md5&digest=80daa08a2415a5a0accf72bb68a018bf (from https://testpypi.python.org/pypi/datalab/); not a file
    Found link https://testpypi.python.org/packages/7e/59/d48d0cacf8a79337632a0beed4124f18b308f9072dfc33e3daf111a7510d/datalab-0.1.1606020925.tar.gz#md5=fbc768fdcffbb76cf6f0fad20b41646b (from https://testpypi.python.org/pypi/datalab/), version: 0.1.1606020925
    Skipping link https://testpypi.python.org/pypi?:action=show_md5&digest=fbc768fdcffbb76cf6f0fad20b41646b (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://github.com/googledatalab/datalab (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://github.com/googledatalab/datalab/tarball/0.1 (from https://testpypi.python.org/pypi/datalab/); unsupported archive format: .1
    Skipping link https://testpypi.python.org/pypi?:action=browse&c=4 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=browse&c=20 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=browse&c=30 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=browse&c=56 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=browse&c=156 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=browse&c=214 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=browse&c=527 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=browse&c=423 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://github.com/edumbill/doap/wiki (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://testpypi.python.org/pypi?:action=doap&name=datalab&version=0.1.1606020925 (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/about/website (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://www.fastly.com/ (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://developer.rackspace.com/ (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link https://aws.amazon.com/s3/ (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.timparkin.co.uk/ (from https://testpypi.python.org/pypi/datalab/); not a file
    Skipping link http://www.python.org/about/legal (from https://testpypi.python.org/pypi/datalab/); not a file
  Using version 0.1.1606020925 (newest of versions: 0.1.1606020925)
  Looking up "https://testpypi.python.org/packages/74/54/2654870a38ed720ee9afc3e5924721bff85cb10f25564f288f036c1d196c/datalab-0.1.1606020925-py2-none-any.whl" in the cache
  Current age based on date: 266
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 266
  Using cached https://testpypi.python.org/packages/74/54/2654870a38ed720ee9afc3e5924721bff85cb10f25564f288f036c1d196c/datalab-0.1.1606020925-py2-none-any.whl
  Downloading from URL https://testpypi.python.org/packages/74/54/2654870a38ed720ee9afc3e5924721bff85cb10f25564f288f036c1d196c/datalab-0.1.1606020925-py2-none-any.whl#md5=80daa08a2415a5a0accf72bb68a018bf (from https://testpypi.python.org/pypi/datalab/)
Collecting oauth2client==2.0.2 (from datalab)
  1 location(s) to search for versions of oauth2client:
  * https://testpypi.python.org/pypi/oauth2client/
  Getting page https://testpypi.python.org/pypi/oauth2client/
  Looking up "https://testpypi.python.org/pypi/oauth2client/" in the cache
  No cache entry available
  "GET /pypi/oauth2client/ HTTP/1.1" 404 28063
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://testpypi.python.org/pypi/oauth2client/: 404 Client Error: Not Found for url: https://testpypi.python.org/pypi/oauth2client/ - skipping
  Could not find a version that satisfies the requirement oauth2client==2.0.2 (from datalab) (from versions: )
Cleaning up...
No matching distribution found for oauth2client==2.0.2 (from datalab)
Exception information:
Traceback (most recent call last):
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pip/req/req_set.py", line 512, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pip/req/req_install.py", line 273, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pip/index.py", line 489, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for oauth2client==2.0.2 (from datalab)
```

**Comment by parthea** [comment]
As a workaround, try using the `--no-deps` option.

First, make sure that you have all the required packages listed [here](https://github.com/googledatalab/pydatalab/blob/master/setup.py)

```
    'future==0.15.2',
    'futures==3.0.5',
    'gcloud==0.14.0',
    'httplib2==0.9.2',
    'oauth2client==2.0.2',
    'pandas>=0.17.1',
    'pandas-profiling>=1.0.0a2',
    'python-dateutil==2.5.0',
    'pytz>=2015.4',
    'pyyaml==3.11',
    'requests==2.9.1',
    'scikit-learn==0.17.1'
```


```
tony@tony-laptop:~$ pip install -i https://testpypi.python.org/pypi datalab --no-deps
Collecting datalab
  Using cached https://testpypi.python.org/packages/74/54/2654870a38ed720ee9afc3e5924721bff85cb10f25564f288f036c1d196c/datalab-0.1.1606020925-py2-none-any.whl
Installing collected packages: datalab
Successfully installed datalab-0.1.1606020925
```

**Comment by yebrahim** [comment]
Closing as obsolete.
