### ISSUE TITLE
Issues with Autentication

### ISSUE THREAD

**Issue by dovy** [googledatalab/pydatalab#437]
It's been working previously, but for some reason pydatalab will not pick up my functioning gcloud settings. It's somehow become "stale." Any ideas?

```
<module 'datalab.storage' from '/Users/dovy/.pyenv/versions/2.7.11/lib/python2.7/site-packages/datalab/storage/__init__.pyc'>
Traceback (most recent call last):
  File "/Users/dovy/.pyenv/versions/2.7.11/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/dovy/.pyenv/versions/2.7.11/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dovy/Development/Sites/nytimes/print_data_warehouse/notebooks/ingest/circroi.py", line 70, in <module>
    source_file=dataproc_config['job']['source_file'] if "job" in dataproc_config and "source_file" in dataproc_config['job'] else ""
  File "notebooks/nyt_pdw/ingest/ingest.py", line 117, in __init__
    source_file = self.get_latest_file(path)
  File "notebooks/nyt_pdw/ingest/ingest.py", line 136, in get_latest_file
    for obj in shared_bucket:
  File "/Users/dovy/.pyenv/versions/2.7.11/lib/python2.7/site-packages/datalab/utils/_iterator.py", line 36, in __iter__
    items, next_page_token = self._retriever(self._page_token, self._count)
  File "/Users/dovy/.pyenv/versions/2.7.11/lib/python2.7/site-packages/datalab/storage/_item.py", line 278, in _retrieve_items
    raise e
datalab.utils._http.RequestException: HTTP request failed: Caller does not have storage.objects.list access to bucket dovy-bucket.
```

**Comment by dovy** [comment]
Found the issue. I had previously logged in under a different account. Somehow pydatalab is storing this information and not using the new session set in gcloud. Any ideas?

**Comment by dovy** [comment]
@ojarjur any ideas?

**Comment by ojarjur** [comment]
@dovy it's a little hard to tell what may be happening since I don't know how your code is calling the API. 

It *looks* like you are creating a `datalab.storage.Items` object and then iterating over it. Was that object created prior to the credentials being changed? If so, it will continue to use the old credentials because it does not pick any changes to credentials after it has been created.

If that is not the case, then we'd have to dig into the [`datalab.context._utils.get_credentials` method](https://github.com/googledatalab/pydatalab/blob/master/datalab/context/_utils.py#L54) to see why the credentials it is picking up are different from the ones you are expecting.

**Comment by dovy** [comment]
@ojarjur I'm not really doing anything different. I had previously been signed into that account for another project, but I have since run gcloud auth revoke. For some reason the pydatalab library kept that data within itself in some cache, despite gcloud not using it anymore.

Is there a cache location? I may try doing some echo statements on that method you outlined. I'll dig in a bit deeper. Thank you.

**Comment by ojarjur** [comment]
@dovy It does use the application default credentials by default if they are set, and those are different from the credentials that are revoked by `gcloud auth revoke`.

Otherwise, I'm not aware of any reason the credentials should be cached.
