### ISSUE TITLE
Incompatibility with Python 3.7

### ISSUE THREAD

**Issue by sam3ay** [googledatalab/pydatalab#711]
**Bug:** 
Importing the datalab module fails in python 3.7

Steps to Reproduce:
```Python 3.7.0 (default, Oct 16 2018, 07:14:15) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google import datalab
```

**Expected:**
Successful import

**Stack Trace:**
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/google/datalab/__init__.py", line 13, in <module>
    from google.datalab._context import Context
  File "/usr/local/lib/python3.7/site-packages/google/datalab/_context.py", line 20, in <module>
    from google.datalab.utils import _utils as du
  File "/usr/local/lib/python3.7/site-packages/google/datalab/utils/__init__.py", line 15
    from ._async import async, async_function, async_method
                            ^
SyntaxError: invalid syntax
```

**Notes:**
Previous versions of python successfully imported datalab, so I'm assuming it's caused by async being a keyword in Python 3.7 hence the syntax error.

**Comment by QuinRiva** [comment]
I'm also getting this issue.  So far by replacing references to **_async_** in ___init__.py_, __async.py_ and __lambda_job.py_ to **_asynchron_** I've managed to get it to import.  I have yet to determine if this will cause any issues down the line.

**Comment by olaoluthomas** [comment]
@QuinRiva Could you provide more details? I've replaced all references to async in the modules you listed and I still get this error:

**Comment by QuinRiva** [comment]
> @QuinRiva Could you provide more details? I've replaced all references to async in the modules you listed and I still get this error:

Sorry, it looks like the issues are somewhat more extensive.  I would be good to determine if this is a live project, as currently many of the dependencies are wildly outdated - in thus incompatible with many of Google's other libraries.

**Comment by slayerjain** [comment]
I'm also facing the same problem.

**Comment by HaipengSu** [comment]
same problem here.

**Comment by migachevalexey** [comment]
same problem here.

from datalab import storage as storage
  File "/env/local/lib/python3.7/site-packages/datalab/storage/__init__.py", line 16, in <module>
    from ._bucket import Bucket, Buckets
  File "/env/local/lib/python3.7/site-packages/datalab/storage/_bucket.py", line 21, in <module>
    import datalab.context
  File "/env/local/lib/python3.7/site-packages/datalab/context/__init__.py", line 15, in <module>
    from ._context import Context
  File "/env/local/lib/python3.7/site-packages/datalab/context/_context.py", line 20, in <module>
    from . import _project
  File "/env/local/lib/python3.7/site-packages/datalab/context/_project.py", line 18, in <module>
    import datalab.utils
  File "/env/local/lib/python3.7/site-packages/datalab/utils/__init__.py", line 15
    from ._async import async, async_function, async_method
                            ^
SyntaxError: invalid syntax

**Comment by rezaprimasatya** [comment]
I got error when using python3.7

from google import datalab
from datalab.context import Context
import google.datalab.storage as storage
import google.datalab.bigquery as bq

any body still have same problem ?
